const RoomTypes = {
    DELUX_DOUBLE_ROOM: 'DELUX DOUBLE ROOM',
    DELUX_SINGLE_ROOM: 'DELUX SINGLE ROOM',
    LUXURY_SINGLE_ROOM: 'LUXURY SINGLE ROOM',
    LUXURY_DOUBLE_ROOM: 'LUXURY DOUBLE ROOM'  
  };

  module.exports = RoomTypes;